
Page({
    onLoad: function(){
        this.setData({
          userinfo:{
            image:'',
            name:''
          },
          list:[
            {
              title:'',
              footer:'',
              cells:[
                {
                  value:'说明',
                  footer:'>',
                  icon:''
                },
                {
                  value:'说明',
                  footer:'>',
                  icon:''
                },
                {
                  value:'说明',
                  footer:'>',
                  icon:''
                }
              ]
            },
            {
              title:'aa2',
              footer:'',
              cells:[
                {
                  value:'说明',
                  footer:'>',
                  icon:''
                }
              ]
            }
          ]
        });
    }
});